import { expect, test } from '@playwright/test'

const { tsImport } = await import('tsx/esm/' + 'api')
const { mkdtemp, rm } = await import('node:fs/' + 'promises')
const { join } = await import('node:' + 'path')
const { tmpdir } = await import('node:' + 'os')
const { once } = await import('node:' + 'events')
const { createMockServer } = await tsImport('../../server/app.ts', import.meta.url)
const { MasterDataSqliteStorage } = await tsImport('../../server/local/master-data-sqlite.ts', import.meta.url)

test('管理员录入真实内容、重载版本、登记引用并验证删除保护', async ({ page }) => {
  const directory = await mkdtemp(join(tmpdir(), 'wrj-master-browser-'))
  const storage = new MasterDataSqliteStorage(join(directory, 'master-data.db'))
  const server = createMockServer({ port: 0, masterDataStorage: storage })
  const errors: string[] = []
  try {
    if (!server.httpServer.listening) await once(server.httpServer, 'listening')
    const origin = `http://127.0.0.1:${server.httpServer.address().port}`
    await page.route('**/api/v1/**', async route => {
      const url = new URL(route.request().url())
      const response = await route.fetch({ url: `${origin}${url.pathname}${url.search}`, headers: { ...route.request().headers(), origin: 'http://127.0.0.1:5173' } })
      await route.fulfill({ response, headers: { ...response.headers(), 'access-control-allow-origin': new URL(page.url()).origin } })
    })
    await page.routeWebSocket('**/ws/v1', () => {})
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    await page.goto('/login')
    await page.getByTestId('login-username').fill('admin')
    await page.getByTestId('login-password').fill('123456')
    await page.getByTestId('login-submit').click()
    await page.waitForURL('**/situation')
    await page.goto('/admin?section=master-data')
    const panel = page.getByTestId('master-data-panel')
    await expect(panel.getByTestId('master-table')).toContainText('暂无匹配的主数据')
    await panel.getByTestId('master-create').click()
    const create = page.getByRole('dialog', { name: '新增主数据', exact: true })
    await create.getByTestId('master-id').fill('DICT-BROWSER')
    await create.getByTestId('master-name').fill('测试通信字典')
    await create.getByRole('button', { name: '新增条目' }).click()
    await create.getByRole('textbox', { name: '参数键', exact: true }).fill('mode')
    await create.getByPlaceholder('文本值').fill('标准模式')
    await create.getByTestId('master-save').click()
    await expect(create).not.toBeVisible()
    const row = panel.getByTestId('master-table').locator('.el-table__row').filter({ hasText: 'DICT-BROWSER' })
    await expect(row).toContainText('测试通信字典')
    await row.getByRole('button', { name: '编辑', exact: true }).click()
    const edit = page.getByRole('dialog', { name: '编辑主数据', exact: true })
    await expect(edit.getByPlaceholder('文本值')).toHaveValue('标准模式')
    await edit.getByPlaceholder('文本值').fill('修订模式')
    await edit.getByTestId('master-save').click()
    await expect(edit).not.toBeVisible()
    await page.reload()
    await expect(row.locator('td').nth(3)).toHaveText('2')
    await row.getByRole('button', { name: '查看', exact: true }).click()
    const details = page.getByRole('dialog', { name: '主数据版本与引用记录', exact: true })
    await expect(details.getByTestId('master-history-table').locator('.el-table__row')).toHaveCount(2)
    await details.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '主数据版本', exact: true }) }).click()
    await page.getByRole('option', { name: '版本 1', exact: true }).click()
    await details.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '引用目标', exact: true }) }).click()
    await page.getByRole('option', { name: /^场景 · .*（SCN-001 \/ \d+）$/ }).click()
    await details.getByRole('button', { name: '登记引用', exact: true }).click()
    await page.getByRole('dialog', { name: '登记主数据引用', exact: true }).getByRole('button', { name: '确认登记' }).click()
    await expect(details.getByTestId('master-reference-table')).toContainText('SCN-001')
    await expect(details.getByTestId('master-reference-table').locator('.el-table__row')).toHaveCount(1)
    await details.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(row.locator('td').nth(4)).toHaveText('1')
    expect(storage.load()[0].content.entries[0].value).toBe('修订模式')
    expect(storage.details('DICT-BROWSER').history[1].content.entries[0].value).toBe('标准模式')
    expect(errors).toEqual([])
    await row.getByRole('button', { name: '删除', exact: true }).click()
    const blocked = page.waitForResponse(response => response.request().method() === 'DELETE' && response.url().endsWith('/admin/master-data/DICT-BROWSER'))
    await page.getByRole('dialog', { name: '删除主数据', exact: true }).getByRole('button', { name: '确认删除' }).click()
    expect((await blocked).status()).toBe(409)
    await expect(panel.getByTestId('master-feedback')).toContainText('不能删除')
    await expect(row).toHaveCount(1)
    // 由公开 API 验证越权，不用篡改前端角色制造证据。
    const forbidden = await page.request.get(`${origin}/api/v1/admin/master-data`, { headers: { Origin: 'http://127.0.0.1:5173', 'X-Demo-Role': 'OPERATOR' } })
    expect(forbidden.status()).toBe(403)
    // 只允许本次明确的引用保护 DELETE 409 所产生的浏览器资源错误。
    expect(errors).toEqual(['Failed to load resource: the server responded with a status of 409 (Conflict)'])
  } finally {
    await page.close()
    await server.close()
    storage.close()
    await rm(directory, { recursive: true, force: true })
  }
})
