import { expect, test } from '@playwright/test'

const { tsImport } = await import('tsx/esm/' + 'api')
const { once } = await import('node:' + 'events')
const { writeFileSync } = await import('node:' + 'fs')
const { join } = await import('node:' + 'path')
const { createMockServer } = await tsImport('../../server/app.ts', import.meta.url)
const { createBackupFixture, BACKUP_TEST_PASSWORD } = await tsImport('../fixtures/system-backup.ts', import.meta.url)

test('SQLite 完整备份、计划保存、损坏拒绝和恢复后主数据回退', async ({ page }) => {
  const f = createBackupFixture()
  const server = createMockServer({ port: 0, backupStorage: f.backup, authStorage: f.auth, scenarioStorage: f.scenario,
    templateStorage: f.template, equipmentStorage: f.equipment, masterDataStorage: f.master, accessControlStorage: f.access, archiveStorage: f.archive })
  const errors: string[] = []
  try {
    if (!server.httpServer.listening) await once(server.httpServer, 'listening')
    const origin = `http://127.0.0.1:${server.httpServer.address().port}`
    await page.route('**/api/v1/**', async route => {
      const url = new URL(route.request().url())
      const response = await route.fetch({ url: `${origin}${url.pathname}${url.search}`, headers: { ...route.request().headers(), origin: 'http://127.0.0.1:5173' } })
      await route.fulfill({ response, headers: { ...response.headers(), 'access-control-allow-origin': new URL(page.url()).origin } })
    })
    await page.routeWebSocket('**/ws/v1', () => {})
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    const login = async () => {
      await page.goto('/login')
      await page.getByTestId('login-username').fill('admin')
      await page.getByTestId('login-password').fill(BACKUP_TEST_PASSWORD)
      await page.getByTestId('login-submit').click()
      await page.waitForURL('**/situation')
    }
    await login()
    await page.goto('/admin?section=database-backup')
    const panel = page.getByTestId('backup-panel')
    await expect(panel).toBeVisible()
    await expect(panel.getByTestId('backup-table')).toContainText('暂无备份记录')
    await panel.getByRole('textbox', { name: '备份名称', exact: true }).fill('恢复演练')
    await panel.getByTestId('backup-create').click()
    await page.getByRole('dialog', { name: '创建备份', exact: true }).getByRole('button', { name: '确认执行' }).click()
    const row = panel.getByTestId('backup-table').locator('.el-table__row').filter({ hasText: '恢复演练' })
    await expect(row).toContainText('校验通过')
    await expect(row).toContainText('全部业务库＋白名单配置')
    const backupId = f.backup.listBackups().find((item: { name: string }) => item.name === '恢复演练').backupId
    await panel.locator('.el-switch').filter({ has: page.getByRole('switch', { name: '启用备份计划' }) }).click()
    await panel.getByRole('textbox', { name: '计划名称', exact: true }).fill('浏览器计划')
    await panel.getByTestId('backup-plan-save').click()
    await page.getByRole('dialog', { name: '保存备份计划', exact: true }).getByRole('button', { name: '确认保存' }).click()
    await expect(panel.getByTestId('backup-plan')).toContainText('下次执行')
    await page.reload()
    await expect(panel.getByRole('textbox', { name: '计划名称', exact: true })).toHaveValue('浏览器计划')
    await expect(panel.getByRole('switch', { name: '启用备份计划' })).toBeChecked()
    await page.goto('/admin?section=master-data')
    const masterRow = page.getByTestId('master-table').locator('.el-table__row').filter({ hasText: 'DICT-TEST' })
    await masterRow.getByRole('button', { name: '编辑', exact: true }).click()
    const edit = page.getByRole('dialog', { name: '编辑主数据', exact: true })
    await edit.getByTestId('master-name').fill('备份之后修改')
    await edit.getByTestId('master-save').click()
    await expect(edit).not.toBeVisible()
    await expect(masterRow).toContainText('备份之后修改')
    const corrupt = f.backup.backup('BROKEN-BROWSER', '损坏演练')
    expect(corrupt.ok).toBe(true)
    writeFileSync(join(f.backup.directory, 'BROKEN-BROWSER.system.db'), 'broken')
    await page.goto('/admin?section=database-backup')
    const damaged = panel.getByTestId('backup-table').locator('.el-table__row').filter({ hasText: '损坏演练' })
    await expect(damaged).toContainText('校验失败')
    await damaged.getByRole('button', { name: '选择恢复' }).click()
    await panel.getByTestId('backup-restore').click()
    await page.getByRole('dialog', { name: '恢复备份', exact: true }).getByRole('button', { name: '确认执行' }).click()
    await expect(panel.getByTestId('backup-feedback')).toContainText('完整性校验失败')
    expect(f.master.load()[0].content.name).toBe('备份之后修改')
    await row.getByRole('button', { name: '选择恢复' }).click()
    await panel.getByTestId('backup-restore').click()
    await page.getByRole('dialog', { name: '恢复备份', exact: true }).getByRole('button', { name: '确认执行' }).click()
    await page.waitForURL('**/login')
    await login()
    await page.goto('/admin?section=master-data')
    await expect(masterRow).toContainText('测试字典')
    await expect(masterRow).not.toContainText('备份之后修改')
    expect(f.master.load()[0].version).toBe(1)
    expect(f.master.details('DICT-TEST').references).toHaveLength(1)
    expect(f.archive.get(f.archived.archiveId)).not.toBeNull()
    expect(f.backup.listBackups().some((item: { backupId: string }) => item.backupId === backupId)).toBe(true)
    expect(errors).toEqual([])
  } finally { await page.close(); await server.close(); f.close() }
})
